### ISSUE TITLE
Display connection settings and macaroons in settings page

### ISSUE THREAD

**Issue by jnewbery** [wbobeirne/joule-extension#101]
At the moment, the only option is 'Reset password and connection settings'. It'd be nice to:

- see the connection settings without having to reset them
- be able to update the REST URL, macaroons and password (#35) separately.

**Comment by jamaljsr** [comment]
I'll work this one

**Comment by jamaljsr** [comment]
I could use some early feedback on the UI for this. Here's the path I'm currently heading down. Suggestions are welcomed.

![image](https://user-images.githubusercontent.com/1356600/50525408-43843780-0aa9-11e9-8feb-e1d1582d5a4a.png)

- clicking *Update* for the Url field will toggle the `disabled` state of the textbox and change the button text to *Save*
- clicking the *Upload* icons for the macaroons will display a modal allowing you to upload a file or enter a hex string. The password will be required to change the Admin macaroon
- clicking *Reset Password* button will display a modal requesting the current password, then prompt for the new password & confirm password
- *Reset All Connection Settings* will keep the existing behavior of clearing everything and displaying the onboarding splash screen

**Comment by jamaljsr** [comment]
Thanks for the detailed feedback. I agree with everything you mentioned. 

Also thanks for the validation tips. I'm expecting that part to be a bit tricky, so the pointers are helpful. I'll keep you posted if I run into any issues.
