### ISSUE TITLE
Unable to install 0.3.0

### ISSUE THREAD

**Issue by arvicco** [wbobeirne/joule-extension#104]
### Description of the Issue

Trying to install the latest (0.3.0) release following the guide at https://medium.com/@pierre_rochard/bitcoin-lightning-joule-chrome-extension-ac149bb05cb9

Getting this error window from Chrome:

----
Failed to load extension
File
~/Downloads/joule-extension-0.3.0
Error
Manifest file is missing or unreadable
Could not load manifest.

----

### Steps to Reproduce

All the steps in the guide up to "Find the Joule folder you unzipped and click on Select"

### Description of Your Setup

*Browser & version*: Crome 70.0.3538.102 (Official Build) (64-bit)
*Operating system*: macOS 10.13.6
*Node software & version*: 

### Console Logs / Screenshots

Extension didn't install

**Comment by PatrickLemke** [comment]
Experiencing the same issue. The manifest.json file seems to be in the wrong folder.

**Comment by wbobeirne** [comment]
The zip of 0.3.0 is for the source code, not the release. I haven't finished releasing it quite yet. I didn't realize pushing a tag would put it on /releases already! Sorry about that.

**Comment by wbobeirne** [comment]
0.3.0 (and 0.3.1) are now properly released. You can also get them in your browser's extension store!
