### ISSUE TITLE
Non-existing transactions shown

### ISSUE THREAD

**Issue by misovan** [wbobeirne/joule-extension#107]
### Description of the Issue

Within Transactions list, weird transactions are shown.

Expected behavior: show list of onchain and lightning transactions (both outgoing and paid invoices). On click, show transaction details in right pane.

Current behavior: 
Within transaction list, 3 separate outgoing lightning payments are shown to 2 nodes I did transactions with. All 3 have the same amount 3 244 570 453 sat. 
Upon click on tx, no tx detail pane is shown, and main pane with tx list dissapears. Side issue: wrong transaction date shown.

Check on my LND node:
`lncli listpayments` does not show such outgoing payments (fortunately).
`lncli listchannels` shows that channels open to concerned nodes have total capacity lower then transactions amount shown.

### Steps to Reproduce

Click on transaction list.

### Description of Your Setup

*Browser & version*: Chrome
*Operating system*: Windows 10
*Node software & version*: Remote node accessed through LAN running LND 0.5.0-beta

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/1290973/50372746-5b087f80-05d4-11e9-98f0-28d184e0c086.png)

![image](https://user-images.githubusercontent.com/1290973/50372754-9b67fd80-05d4-11e9-9ea4-c60d13c703a1.png)

`lncli listpayments` response

![image](https://user-images.githubusercontent.com/1290973/50372786-2d700600-05d5-11e9-87a3-06fdaf40a8fe.png)

**Comment by wbobeirne** [comment]
That's really strange, thanks for the report. If you could do me a few favors to help debug, that'd be really appreciated:

* When you click on the faulty transactions, do you get any errors in the console?
* When you load the transactions tab, can you get the network responses for the 3 network requests it makes? The erroneous data is probably in  `/v1/payments` but looking at all 3 may help.

You can open the console by right clicking the icon, and clicking "Inspect popup". There's also a network tab in there.

**Comment by misovan** [comment]
Here it is:
1. Console on loading tx tab looks OK - api calls return correct responses from my LND instance:
![tx_debug1](https://user-images.githubusercontent.com/1290973/50453338-35ff6e00-0940-11e9-9b91-5de09ac46065.png)


2. Console after having clicked on invalid tx:
![tx_debug2](https://user-images.githubusercontent.com/1290973/50453342-3dbf1280-0940-11e9-8aaf-4214a7d20a08.png)

**Comment by wbobeirne** [comment]
OK, this is definitely much more to work with. Can you actually click on "payments" in the network tab, and paste the response from it in full (feel free to omit any sensitive data!)

**Comment by misovan** [comment]
Hi, I checked them, they look OK. I searched for numeric strings in responses like 3244* and there are not. Really strange :)
