### ISSUE TITLE
Be able to connect to Opennode or Strike using Apis.

### ISSUE THREAD

**Issue by bitcoinuser** [wbobeirne/joule-extension#123]
Hi,

As I can see https://www.opennode.co/ and https://strike.acinq.co/ services have Apis. I know this service allow to connect to them: https://tallyco.in/

I think Joule could allow users to connect to Strike or Opennode. So I could use my funds on Opennode to pay or request bitcoin.

Thanks.

**Comment by bitcoinuser** [comment]
Hi,

If a service has an API, I'm sure they want to be integrated on any other service, including Joule. This hardware devices are good and ideal, but for people on countries underdeveloped, it's yet expensive to buy it. I think you should give people as many options as possible. So my suggestion is to add services like Strike or Opennode to Joule.

**Comment by jamaljsr** [comment]
These third-party services provide API's to receive payments, not send them. The need they fill is to allow businesses to accept lightning payments by integrating the merchant's shopping cart or POS system with OpenNode/Strike. Then users can purchase their products/services with btc/lightning.

Joule is a wallet for users to store and send payments. Joule is on the opposite side of the transaction and therefore there is no integration to be done. Lightning is the language both sides speak to fill the gap. The best solution you could have is for those payment processors to add WebLN to their plugins to streamline the payment flow for users.
