### ISSUE TITLE
Transaction list fails when I have a payment to a non-existing node

### ISSUE THREAD

**Issue by vegardengen** [wbobeirne/joule-extension#141]
### Description of the Issue

Clicking on the "Transactions" button, I get 

Failed to fetch transactions
unable to find node

### Steps to Reproduce

Clicked on transactions when I had a payment to a node that no longer exists/can be found in my graph

### Description of Your Setup

Chrome 70.0.3538.77
Ubuntu 18.04
LND 0.5.1-beta commit=v0.5.1-beta-258-gf7fb9486b4bd4b9e74e933b4a7b734edd7e71d8
### Console Logs / Screenshots

02a4a8212afe89aa2983b97c0a8a36d074fa283820213a404b1ec6a202b3fd5f03:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:8 API error calling GET /v1/graph/node/02a4a8212afe89aa2983b97c0a8a36d074fa283820213a404b1ec6a202b3fd5f03 Error: unable to find node
    at r (index.js:9)
    at t.<anonymous> (index.js:8)
    at index.js:8
    at Object.next (index.js:8)
    at o (in

I can see that there is only one request to /v1/graph/node/* that gave
{"error":"unable to find node","code":2}

**Comment by wbobeirne** [comment]
Thanks for the report! This was fixed with #124, but hasn't made it into a new release yet. I'm hoping to have one out soon. Sorry for the inconvenience.
