### ISSUE TITLE
Fail to show Transactions using BTCPay

### ISSUE THREAD

**Issue by slack333** [wbobeirne/joule-extension#143]
### Description of the Issue

When I open Joule and then I go to "Transactions" it shows "Fail to fetch transactions"

### Steps to Reproduce

1. Open Joule (connected to BTCPay)
2. Go to "Transactions" tab

### Description of Your Setup

Chrome
Windows & Mac
BTCPay Server - LND

### Console Logs / Screenshots
![image](https://user-images.githubusercontent.com/25033440/51251766-cbf34b00-1978-11e9-8f49-d184a401154f.png)

**Comment by wbobeirne** [comment]
This is the same as #141, which was fixed in #124. That's been fixed on master, but I need to make a new release before it'll be fixed in the current release. Sorry for the inconvenience, expect a new release soon.
