### ISSUE TITLE
Trouble building extension

### ISSUE THREAD

**Issue by brandoncurtis** [wbobeirne/joule-extension#15]
I've attempted to clone, build, and link webln:
```
git clone git@github.com:/wbobeirne/webln
cd webln
yarn
yarn link
```
and then clone and build joule-extension:
```
git clone git@github.com:/wbobeirne/joule-extension
cd joule-extension
yarn link webln
yarn
yarn run build-dev
yarn run dev
```

node: v10.13.0
npm: v6.4.1
yarn: v1.12.1

This does not appear to build a manifest file in ./dist, so I'm unable to install the unpacked extension.

Did I skip a step?

**Comment by wbobeirne** [comment]
That's embarrassing, you're 100% correct. I had hard-coded a couple of the files to dist, but they were obviously `.gitignore`d. I'll get webpack to build them correctly at some point, but in the mean time, I'll go ahead and push up the missing files.

**Comment by wbobeirne** [comment]
Pushed with 727f5174ddb0ae9550616247873bf5955ee4d3c9, thanks again for letting me know.
