### ISSUE TITLE
Bad link on your landing page

### ISSUE THREAD

**Issue by justinmoon** [wbobeirne/joule-extension#155]
GitHub link in the footer of https://lightningjoule.com/ points to https://github.com/wbobeirne

https://github.com/wbobeirne/joule-extension/ would be better IMO

**Comment by jnewbery** [comment]
Also the twitter link on https://lightningjoule.com/contact says @WBOBEIRN but points to @lightningjoule

**Comment by jnewbery** [comment]
(issue should be in https://github.com/wbobeirne/joule-splash)

**Comment by justinmoon** [comment]
Filed over there. Thanks John. https://github.com/wbobeirne/joule-splash/issues/2
