### ISSUE TITLE
Can't connect to my LN node

### ISSUE THREAD

**Issue by rookey** [wbobeirne/joule-extension#156]
I also seem to have TLS handshake error while connecting, albeit a different one than described in the other thread.

I'm trying to connect via "Local node" from my desktop computer in Firefox 64.0.2, which is on the same network as my LND node (192.168.10.5).
Entering https://192.168.10.5:8080 as node url results in "Failed to connect to node", clicking the link results in a timeout error message. However, I can ping the ip from the command line or with putty just fine, the node is online. 
At one point, 'sudo journalctl -u lnd -f' showed "lnd[1025]: 2019/01/28 16:00:35 http: TLS handshake error from [::1]:55526: EOF" - but I was never able to get this error status message again, so I'm not sure if it was even caused by my efforts to connect Joule?

My /home/bitcoin/.lnd/lnd.conf:

```
# RaspiBolt: lnd configuration
# /home/bitcoin/.lnd/lnd.conf

[Application Options]
debuglevel=info
maxpendingchannels=5
alias=LND@BitcoinH
# alias=YOUR_NAME [LND]
color=#68F442
restlisten=0.0.0.0:8080
tlsextraip=0.0.0.0

# Your router must support and enable UPnP, otherwise delete this line
# nat=true
externalip=123.123.123.123 (anonymized by me)

[Bitcoin]
bitcoin.active=1
```

Any idea what I can do to fix this?

**Comment by seth586** [comment]
I don't think `tlsextraip` can be defined as a range, try deleting it?

The following lnd.conf https connection works for me on a LAN subnet:
```
[Application Options]
; set external IP if not using NAT
externalip=xxx.xxx.xxx.xxx
listen=0.0.0.0:9735
restlisten=0.0.0.0:8082
; set node alias (seen in explorers)
alias=myname

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
```

**Comment by rookey** [comment]
hmm… it didn't show, but now I've added it but still can't connect. This is really odd..

**Comment by wbobeirne** [comment]
I'm going to close this out since it seems like it's an issue specific to your node / network setup. Sorry I couldn't be of more help.

**Comment by rookey** [comment]
Okay, np. After a few changes, now when I try to connect to Remote node (my fixed IP), I get no connection at all.
Trying to connect to "Local Node" with https://192.168.10.5:8080  (192.168.10.5 is my Raspberry), I can't get connected receiving the message "Request failed with the message "Not Found"".

The [ApplicationOptions] section in my lnd.conf is:

```
[Application Options]
debuglevel=info
maxpendingchannels=5
alias=MyRealNodeName
color=#68F442
restlisten=0.0.0.0:8080
listen=0.0.0.0:9735
# rpclisten for Shango access
rpclisten=0.0.0.0:10009
tlsextraip=0.0.0.0
tlsextraip=192.168.10.5

```
sudo -netstat -ltnp | grep 8080 gives me
/home/bitcoin/.lnd $ tcp6       0      0 :::8080                 :::*                    LISTEN      3498/lnd

Any idea what I could do to at least be able to connect locally?

**Comment by yellowcookies** [comment]
experiencing the same problem. it's definitely a port problem because i can connect with joule if it is running on the same computer (in this case my bitseed3 node with lightning installed). still haven't quite figured it out though, double and triple checked the ports are open, in use and forwarded. RT-AC3200 router both devices wired. needless to say im fkn STUMPED.

**Comment by yellowcookies** [comment]
this was not a network problem this was a settings problem in LND.

changed restlisten=127.0.0.1:8080 in ~/.lnd/lnd.conf to local ip of device. did not change anything else and it worked like a charm.
