### ISSUE TITLE
Add support for Zap button in onboarding

### ISSUE THREAD

**Issue by JimmyMow** [wbobeirne/joule-extension#158]
Zap users frequently request my help for getting set up with Joule. I've noticed recently there is a `Lightning App` on-boarding button that looks to scan for the Lightning App's default port.

<img width="680" alt="screen shot 2019-01-31 at 4 52 31 pm" src="https://user-images.githubusercontent.com/4040039/52091133-09f78e00-2579-11e9-9560-70dae0fe23f4.png">

I think there should be a Zap Desktop on-boarding button as well. Our default port is `8180` (source: https://github.com/LN-Zap/zap-desktop/blob/master/app/lib/lnd/neutrino.js#L29)

**Comment by wbobeirne** [comment]
Hey, just looking into this now. Is there also a usual spot for macaroons to be?

**Comment by wbobeirne** [comment]
Ah, found them in `~/Library/Application Support/Zap/lnd/bitcoin/[network]/[name-of-wallet]`. This might be tricky for users who have more than one wallet though, as there's no distinguishing naming between them, just a random number. It'd be awesome if Zap had an option to open the folder that contains all the goods.

**Comment by mrfelton** [comment]
Is there any way for Zap to communicate with Joule? Does Joule provide an accessible API of it's own?

**Comment by wbobeirne** [comment]
No, chrome extensions are completely sandboxed. It's possible to implement native app communication through the [Native messaging API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) but that would require some Joule-specific implementations on Zap's side that I don't imagine us collaborating on in the short term. I'm totally open to any suggestions from the Zap team though, if there's a desire to do so!
