### ISSUE TITLE
HandShake Error when Connecting Local / Remote 

### ISSUE THREAD

**Issue by lrgeoemtry** [wbobeirne/joule-extension#165]
### Description of the Issue

took the URL from pierre's node launcher 
tried to put remote on different device, visible handshake error from ip

tried to put node url locally
same issue 

### Steps to Reproduce

[Explain what you did to experience the issue]

### Description of Your Setup

*Browser & version*: up to date chrome
*Operating system*: windows 
*Node software & version*: LND 5.4 

lemme know what you can do to help!

**Comment by jamaljsr** [comment]
I may be able to help. Can you share a screenshot of the error your seeing?

**Comment by lrgeoemtry** [comment]
i got it to work!
