### ISSUE TITLE
Failed to connect to node

### ISSUE THREAD

**Issue by babonet13** [wbobeirne/joule-extension#173]
I have a running LND node on a local machine

### Description of the Issue

See screenshot

What to check in the server side in order to solve this issue
![capture d ecran 2019-02-19 a 18 41 05](https://user-images.githubusercontent.com/20139338/53035684-492d4680-3476-11e9-9bc1-430c2746c0ee.png)

**Comment by wbobeirne** [comment]
Can you check the link in the error to see what it's spitting out? This looks as though you're pointing it towards a non-LND server, like something that's returning HTML.

**Comment by babonet13** [comment]
I got this

![dggest](https://user-images.githubusercontent.com/20139338/53110710-e1d9ca00-353b-11e9-9b0e-4684023bf751.png)

**Comment by babonet13** [comment]
I got this

![capture d ecran 2019-02-20 a 18 17 55](https://user-images.githubusercontent.com/20139338/53110739-f918b780-353b-11e9-969f-0ed10413d88e.png)

**Comment by PJUllrich** [comment]
Just a thought: Have you tried putting `https` instead of `http` in front of the IP? Some (all?) LND nodes only support `https`.

**Comment by wbobeirne** [comment]
Based on the response he got, I'm convinced something other than LND is listening in on port `8080` and responding here. I can't think of any reason LND should do that.

@babonet13 you probably want to get access to that machine's terminal and run `netstat -ltnp | grep 8080` to see what's running. My guess is it's not LND.

**Comment by babonet13** [comment]
> Just a thought: Have you tried putting `https` instead of `http` in front of the IP? Some (all?) LND nodes only support `https`.

@PJUllrich 

In this case, I got this :
![capture d ecran 2019-02-22 a 18 24 39](https://user-images.githubusercontent.com/20139338/53259420-4a0ce500-36cf-11e9-9c9b-47ec6745e87a.png)

**Comment by babonet13** [comment]
> Based on the response he got, I'm convinced something other than LND is listening in on port `8080` and responding here. I can't think of any reason LND should do that.
> 
> @babonet13 you probably want to get access to that machine's terminal and run `netstat -ltnp | grep 8080` to see what's running. My guess is it's not LND.

@wbobeirne 

I got this result : 
<img width="898" alt="capture d ecran 2019-02-22 a 18 22 58" src="https://user-images.githubusercontent.com/20139338/53259476-70328500-36cf-11e9-92c1-616a8f15d7bd.png">

**Comment by wbobeirne** [comment]
OK, looks like HTTPS is working fine then. You should connect with that URL instead, and it looks like it should work. Let me know if that's not the case.

**Comment by babonet13** [comment]
Sorry, do NOT work !
Which test I can achieve in order to solve this issue ?

**Comment by wbobeirne** [comment]
Can you describe what happens when you try the HTTPS url? Did you follow the instructions in the error to whitelist the SSL certificate?

**Comment by babonet13** [comment]
I have upgraded my LN node to the last version ...
... and it workd fine now.
Many Thanks for Support !
