### ISSUE TITLE
App crashes on apparently malformed tx reported from lnd

### ISSUE THREAD

**Issue by bilthon** [wbobeirne/joule-extension#175]
### Description of the Issue

There is a very specific on-chain transaction that when clicked will make the app crash. After checking the logs at the developer console, I can see the following stack trace:

```
TypeError: "o.amount is undefined"
    render schedule.production.min.js:10 Jr9React
```

And indeed if I issue `lncli listchaintxns`, I find this to be the problematic entry:

```
        {
            "tx_hash": "17ae78708a7723d8b1ea727c28970fe479730d5f3a16a8127d234becea29108e",
            "amount": "0",
            "num_confirmations": 35,
            "block_hash": "00000000000000000010cb3d78ee807c11d0f22a15201286a1c3ba5098bb121d",
            "block_height": 563986,
            "time_stamp": "1550728921",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qv34q5kwx8nnrfqmfdasrlesu0zkdzl3z7ylv62",
                "bc1qfm750p5pvzst0hufvvtvv4sqrqws7h6huegalrfhjvj3pwjgdxfqen69ke"
            ]
        }
```

I suppose the `amount` field cannot be zero. Because really, how can it be? This is probably an issue with `lnd` or `lncli` that is being carried over to Joule. But I suppose the app should at least handle it and filter out the offending tx instead of just crashing.

As a matter of fact, I don't recall opening that channel and I'm not using autopilot, so it is possible (although I'm not sure) that this was not a transaction of my wallet at all. That would explain why the amount is zero.

### Steps to Reproduce

It's hard to reproduce since you'd have to have this kind of (apparently malformed) transaction.

### Description of Your Setup

*Browser & version*: Firefoz Quantum 65.0.1 (64-bit)
*Operating system*: macOS 10.14.3
*Node software & version*: lnd version 0.5.2-beta commit=v0.5.2-beta, lncli version 0.5.2-beta commit=v0.5.2-beta

### Console Logs / Screenshots
[Screen record](https://imgur.com/zPtWrY4)

**Comment by wbobeirne** [comment]
Hey @bilthon, thanks for reporting. I'm happy to say this has been fixed with #159, but I haven't made a new release yet. Planning on making one some time this weekend. Sorry for the inconvenience!
