### ISSUE TITLE
Accounting totals seems to be off

### ISSUE THREAD

**Issue by dmp1ce** [wbobeirne/joule-extension#178]
Nearly ever time I try to total up transactions I get a small discrepancy in the accounting in comparison to what Joule is telling me. I don't know if it is LND, Joule or the way I am totaling transactions. I am just adding up all of the amounts and fees from each transaction. Am I missing something? Is there a hidden fee that LND takes for routing which Joule does not expose?

It is probably just me but I do often see a discrepancy when paying for articles on yalls. I recently saw a discrepancy of 0.00016609 BTC after purchasing some articles and I couldn't see I had made any mistakes in my tally.

**Comment by wbobeirne** [comment]
It's hard to be sure without having full access to your transaction history, but that amount sounds inline with the on-chain fee of opening a channel. Could that be the missing piece?

**Comment by dmp1ce** [comment]
I think I'm including the fee for opening channels. The balance seems to change every day or two. I'm not sure why. Maybe autopilot on LND? I'm really not sure. I don't think it is a Joule issue though, because balances seem to reflect what is in LND.

**Comment by dmp1ce** [comment]
I woke up today and my balance had changed by 169 sats. I haven't made any transactions since last night. I must be missing something on my node that is causing the balance to change.

**Comment by wbobeirne** [comment]
Hmm, hard to say, could be related to routing? Either way, I do think this falls on LND as we're just rendering what it returns. Sorry I can't be of more help!

**Comment by dmp1ce** [comment]
On IRC it was mentioned that the LND balance changes for version 0.5.2-beta because of the commit fee. There are was to prevent this with newer versions from my understanding.

**Comment by marsrobertson** [comment]
# Same here

Maybe better explain in the UI why there is a difference?

![image](https://user-images.githubusercontent.com/44369284/58547908-2f7f6600-8200-11e9-969e-0759a4cda279.png)


`lncli listchannels`

```
            "capacity": "100000",
            "local_balance": "68685",
            "remote_balance": "0",
            "commit_fee": "31315",
            "commit_weight": "600",
            "fee_per_kw": "43254",
```

**Comment by wbobeirne** [comment]
This ended up getting moved into #194
