### ISSUE TITLE
Unlock symbol on password prompt fails to submit the form

### ISSUE THREAD

**Issue by brandoncurtis** [wbobeirne/joule-extension#18]
Clicking the unlock symbol on the password prompt fails to submit the form.

![screenshot from 2018-10-31 00-35-28](https://user-images.githubusercontent.com/2591290/47772852-36172080-dca5-11e8-807a-5ebffab0560a.png)

Hitting enter on the keyboard submits the password and completes the payment.

**Comment by wbobeirne** [comment]
Good catch, I caught this as well on a local branch that also implements the deposit modal. That should go up shortly. Thanks for reminding me!

**Comment by wbobeirne** [comment]
Closed via #22.
