### ISSUE TITLE
Add fee selection to Open Channel form

### ISSUE THREAD

**Issue by jamaljsr** [wbobeirne/joule-extension#181]
### Description of the Feature or Idea

This issue was brought up in this tweet: https://twitter.com/citlayik/status/1103914960952815617
It suggests that LND can overpay transaction fees at times. I have been unable to confirm this myself, but it doesn't hurt to give users more control. Since we recently introduced fee selection for sending on-chain transactions, it makes sense to also add it for opening a channel as well.

**Comment by robclark56** [comment]
+1

I am using Joule. But when I wanted to open a channel using "--sat_per_byte 1", I had to do it with the lncli CLI.

**Comment by jamaljsr** [comment]
Interesting. I didn't implement the ability to manually specify an exact sats/byte amount, but I think that can be easily added without cluttering the UI.

**Comment by jamaljsr** [comment]
@robclark56 The option for 1 sat/byte fee has been added to the PR. Thanks for the feedback 👍

**Comment by robclark56** [comment]
Good to see you have added the sat/byte option.

But the way I read what you have said is that the user will only have 2 options:
1)  same as before i.e. no sat_per_byte set
2) 1 sat_per_byte

sat_per_byte options really need to be:
1) Not set by user = default = lnd works out what miner fee to set
2) User input (integer, non-zero)

```
lncli openchannel -h
   --sat_per_byte value      (optional) a manual fee expressed in sat/byte that should be used when crafting the transaction (default: 0)
```

**Comment by robclark56** [comment]
Ignore comment above ... just looked at the PR and is is extremely comprehensive.

🥇
