### ISSUE TITLE
Cannot connect Joule to `lnd` within extension pop-up window

### ISSUE THREAD

**Issue by brandoncurtis** [wbobeirne/joule-extension#20]
When the Joule extension pop-up loses focus, it disappears and reverts to the extension's home page.  This makes it impossible to select the macaroons when connecting Joule to `lnd`.  The same issue makes it difficult to retrieve a password from a password manager to unlock Joule while paying a copied-and-pasted Lightning Network invoice.

The best workaround is to open Joule in its own page by navigating to e.g. `chrome-extension://lnbbaakgapeflbgngbbjhmnjfhidhlhe/popup.html`.  Joule can then be successfully connected to `lnd`.

To remedy this, it would be helpful if the Joule pop-up included a link to the full-page view, and/or if the extension window could be made to persist even when it loses focus.

**Comment by wbobeirne** [comment]
This is a great point, I'd been clicking on the inputs and navigating to my macaroons, but if you tried to drag, it definitely would close. I'll put together an `options.html` page, and the "Get started" button will bounce you over there for setup.

**Comment by wbobeirne** [comment]
Whoops, meant to close #18, not this one.
