### ISSUE TITLE
Joule handle links with lightning URI when requestProvider is rejected

### ISSUE THREAD

**Issue by alepop** [wbobeirne/joule-extension#203]
### Description of the Issue

If you reject `requestProvider` prompt by WebLN, links with `lightning:` protocol still be handled by `Joule` extension. It's happening because links handler send an event directly to Joule through sendMessage event, while `JouleWebLNProvider` methods check `isEnabled` attribute before making the same.

https://github.com/wbobeirne/joule-extension/blob/629a29f156d2f35f7a1853a8b8bf9598367867a3/src/content_script/index.ts#L55
### Steps to Reproduce
- call `requestProvider`
- reject it
- click on a link with href which contains `lightning:` URI
- joule will open a `sendPayment` prompt

@wbobeirne what if use `JouleWebLNProvider` methods in `inpage_script` instead of posting a message?

**Comment by wbobeirne** [comment]
This was actually intentional on my end, as rejecting requestProvider was meant to prevent a website from directly interacting with your node via WebLN methods. But clicking on links is something you're doing to trigger the action, so that was fine with me.

Is the issue here that you anticipate people to reject with the intent of opening in another wallet?

**Comment by alepop** [comment]
I thought that `Joule` was designed to communicate with a user through the webln provider. If not, then I don't see the issue here. But it confuses me a little bit when I rejected `requestProvider` but click on a link still trigger Joule prompt.

**Comment by wbobeirne** [comment]
Yep, I can definitely see the confusion there. Joule supports both links _and_ WebLN for backwards compatibility. Perhaps I should add a note to the authorization window to indicate that links will still work.

Thanks for the notes, I'm going to close this for now as I'm planning to revamp that screen to provide more information and granular access in the near future.
