### ISSUE TITLE
Send bitcoin transactions

### ISSUE THREAD

**Issue by wbobeirne** [wbobeirne/joule-extension#31]
There's a form for sending lightning transactions, but bitcoin transactions are also possible using the [`POST /v1/transactions` API](https://api.lightning.community/rest/index.html#v1-transactions).

**Comment by juscamarena** [comment]
Would be great to ask to pay the fallback address if it can't be paid through lightning (not enough balance or something) or even just pick up bitcoin: uri as well and make a similar view to pay that.
