### ISSUE TITLE
Newbiw question: Is it possible connect BLW with Lightningjoule

### ISSUE THREAD

**Issue by bitcoinuser** [wbobeirne/joule-extension#49]
Hi,

I have this lightning wallet on my android: https://lightning-wallet.com/
I would like to know if it's technically possible connect lightningjoule with BLW. For example: I have my BLW wallet with channels opened.... So I think I have a node, right? So I could use something like what you describe as macaroon, and connect my BLW "credentials" to Lightningjoule.

Thanks.

**Comment by wbobeirne** [comment]
Unfortunately I don't think mobile wallets will expose macaroons, or have the REST API configured, nor would the phone have a static IP for Joule to reliably connect to. I think it's unlikely that these types of light clients will ever work well with Joule.

I think the most likely solution we'll have going forward is having one dedicated remote node (Whether you own it at home, rent it remotely, or use a custodial node service) that your phone connects to in the same way as Joule. But it's still early days, so there may be better ways to have client interoperability!

Sorry I couldn't be of more help!

**Comment by bitcoinuser** [comment]
Hi, thanks for the answer. 

What I mean or wanted is some way the lightningjoule extension could connect with a bitcoin lightning android app with some tecnology like for example bluetooth. So If I have my phone near my computer, I could "syncronize" the android lightning wallet with lightningjoule and make payments using my browser. I think this could be amazing. I don't think lightningjoule should have option to open channels..... Should just allow make payments or invoices and deposit.
