### ISSUE TITLE
Scan more ports for local node setup

### ISSUE THREAD

**Issue by wbobeirne** [wbobeirne/joule-extension#51]
Looks like there are some instances of apps setting up the REST api on different ports. I'll try to keep a list of them all here, but we should scan them all:

* 8080 - LND default
* 8086 - [Lightning App](https://github.com/lightninglabs/lightning-app/blob/9b069586f11bdbd7cf8817ebe7ff5b7ab0534320/src/config.js#L13)

**Comment by bitcoinuser** [comment]
Newbie question: If I install Lightning App from lightning labs and install lightningjoule extension and try Local Node on Lightningjoule, will not find it, correct? 
I'm with Lightning App opened and tried to make lightningjoule work, but it didn't work as you can see in the image:

![captura de tela de 2018-12-01 21-29-45](https://user-images.githubusercontent.com/1178856/49333961-49712080-f5b0-11e8-9618-96bf7bb04a90.png)

**Comment by wbobeirne** [comment]
Yep, that's precisely what this issue is about.
