### ISSUE TITLE
WordPress Plugin Installation

### ISSUE THREAD

**Issue by VidYen** [wbobeirne/joule-extension#62]
Hi, this might be something for me to do rather than request you to make a plugin for WordPress. But for the web site owner, I deal with a lot of non-technical users. Is there an implementation for this for installing on WordPress sites? As in... What does a site admin need to have in order to put this on their website? I do a good deal of plugin bridging for rewards sites between crypto plugins and various other store and/or rewards systems.

I know most of them aren't technical knowledgeable to run their own nodes, but I know Dashed-Slug's plugin uses Coinpayments.net as a node (option to run a regular BTC node was in a long time ago), so if you could use a trusted node or even I could run one for them as I already do that with a browser mining stratum.

What would be the technical requirements (server setup) required for a WordPress install... Its given they have at least PHP 5.* and cPanel and although that usually is CentOS, many of them don't have SSH to do terminal stuff.

With my browser miner stuff, I rent Debian servers, but perhaps I should get your view on if this is possible, already done in a plugin somewhere, or not a good idea. I could maybe even ask Dashed Slug if he has something in the works.

**Comment by wbobeirne** [comment]
I'm not really sure I follow how you envision Joule would work as something that's served on page. The point is to have the user's node be connected to your page. So unless the user were to provide your page with all of the connection information and macaroons (Which would be very insecure) you wouldn't be able to do this kind of communication.

If your hope is to have wordpress sites handle payments, invoice generation, or user identification _from_ Joule, this could definitely be done through a plugin that adds [WebLN functionality](https://github.com/wbobeirne/webln) to the site. Perhaps an existing plugin like https://github.com/joaodealmeida/woocommerce-gateway-lightning could be leveraged for payments? I'd imagine something much more custom would have to be done for the other things.

**Comment by wbobeirne** [comment]
OK, there's not much the Joule extension can offer to help in this regard _except_ whatever plugin does this can use WebLN to prompt the user to generate a BOLT-11 string using `webln.makeInvoice`.

However, I don't think I'm your guy to develop that plugin! I'm going to close this issue, since I'm not sure I can contribute much to what you want. But if you have ideas of how what Joule can do to this end, let me know.
