### ISSUE TITLE
Show pending channels

### ISSUE THREAD

**Issue by wbobeirne** [wbobeirne/joule-extension#71]
When you create a new channel, it's visible via https://api.lightning.community/rest/index.html#v1-channels-pending until it's confirmed. We should query and display this as well.

**Comment by jnewbery** [comment]
Sounds good.

There's also the rather user-unfriendly behaviour that `walletbalance` does not include balances from pending channels. If launched with autopilot, the user's balance decreases when channels are opened until they reach the required number of confirmations. Perhaps it'd be friendlier behaviour if the balance shown in Joule also showed balances from pending channels?

**Comment by wbobeirne** [comment]
Yes, I had exactly this experience today. I'll probably just change that display to use `totalBalancePending` rather than `totalBalance`. I had questioned whether it was a worse experience to show a user's balance they couldn't access yet, or to not show it at all, I definitely think I chose wrong. I can probably add a little icon / tooltip when some is pending that, when hovered over, shows your available balance.

**Comment by bitcoinuser** [comment]
Hi,

In my opinion you should show total balance (including the one that couldn't be acessed yet). 

I have an money app that it's not related to crypto but have an interesting structure.

1- They show on main window the (Total Balance = Money in account)
2- When the user click on Total Balance, appear a new window that shows:

* **Money in account** (total balance): 50 dollars
* **Available money** (Money that you can spend now): 40 dollars
* **Pending deposit** (money that you own but need some time to be able to be spent): 10 dollars
* **Money to be released** (Money the user redeemed to an external bitcoin address): 40 dollars

3- In front of **Available money** could have a button (withdraw), so when users click on it, joule will ask the total amount to withdraw and the bitcoin address to send it. When user fill the information, joule will tell user that channels a, b or c will be closed to proceed the withdraw and that the process will take some time. 

4- When user click on **Money to be released** could show the information of when approximately the withdraw process will end. The same thing for **Pending deposit**.

5- I think joule could have only the option to deposit bitcoins to open channels. Maybe an option to user select if he wants to open channels automatically or no. But I think the process to send on-chain bitcoin should appear only on withdraw specified on item 3.

6- On main window of Joule you should keep just * **Money in account** and not the Channels and Bitcoin as it's now.

Thanks.

**Comment by callmekurisu** [comment]
I got pending force close on the list. Should be able to get the pending open channels done soon. 

![image](https://user-images.githubusercontent.com/13033037/50546901-7f2c1800-0bf5-11e9-9b80-8bab2f67584d.png)
