### ISSUE TITLE
Paying invoice without numerical amount fails

### ISSUE THREAD

**Issue by erikbos** [wbobeirne/joule-extension#75]
Parsing an invoice where amount is not set to a numerical value fails:

type mismatch, parameter: amt, error: strconv.ParseInt: parsing "undefined": invalid syntax

e.g.

lnbc1pwq6e83pp5vxfk7n7z2rh27p60cnzsgy9txdamv948aka7nv5kjnnxtm0j2zgqdpsgejk2erfdenjqarfwpcxjm3wd4jjqum9wfmx2unnyrcflr9wcqzysxqzjcc7chlhzh0qeuvud0g67llyxujxqz39e5sjhy290vu34n3g6r0e5h0jgwl0dug0c6ysf6xaaqtdh3jat58284s48hvpkf0rug0q9gwxspkx0wgu

**Comment by erikbos** [comment]
https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md

states that the reader must fail when the amount is not numerical, so the issue is on the invoice generator side.

**Comment by wbobeirne** [comment]
This actually is a valid point! The `undefined` is coming from my code, but this is in fact a use-case outlined in BOLT-11 that I didn't account for, amount can be unspecified. For example, tippin.me relies on this.

> amount: optional number in that currency, followed by an optional multiplier letter. The unit encoded here is the 'social' convention of a payment unit -- in the case of Bitcoin the unit is 'bitcoin' NOT satoshis.
> ...
> If the amount is empty:
> SHOULD indicate if amount is unspecified
> ...
> Donation addresses often don't have an associated amount, so amount is optional in that case. Usually a minimum payment is required for whatever is being offered in return.

So I'll need to add an `amount` input to the send forms if one is not specified.
