### ISSUE TITLE
Using Joule as standard lightning link application

### ISSUE THREAD

**Issue by PatrickLemke** [wbobeirne/joule-extension#76]
I am using Chrome and when I click lightning links sometimes they want to open Zap Wallet instead of the Joule extension. Is there a way to make Joule the default? I tried to follow some guides with mailto links but they didn't work for me.

**Comment by wbobeirne** [comment]
Unfortunately extension support for intercepting application links like `lightning:` is really bad, so I'm using a link click listener. If applications are using `window.location.href = "lightning:..."` for instance, it won't intercept that. Do you know which applications are failing?

The other possibility is there's an error in the code and it's failing to bind. Can you check your javascript console when this happens and let me know if you see anything error-y looking?

**Comment by PatrickLemke** [comment]
For example if I try to pay for an article on yalls.org, sometimes I will get the Joule popup, but sometimes it will ask to open Zap Wallet. I think it's after the application is installed it works for a while and then it stops working. I am not sure if yalls.org uses different link formats each time.

**Comment by wbobeirne** [comment]
Alright, I'll stress test this and see if I can replicate. Thanks for the info!

**Comment by wbobeirne** [comment]
I noticed that tippin.me is doing
```
onclick="location.href='lightning:ln..."
```
which does not work, as I suspected. I haven't been able to get this to happen on yalls.org though, so perhaps a separate issue. Unfortunately, I don't think there's much I can do about the location.href redirects, but I'll dig into that.

**Comment by PatrickLemke** [comment]
Thanks for looking into it, I guess the problem is that I have no clue where Chrome stores the default handlers for lightning links. I can't find it anywhere in the settings or on the internet. If I remove Zap completely or reinstall Chrome it works since there is no other options for chrome to choose. Maybe it's some setting that Zap uses that makes some changes to the OS since it's more of a native app. I will chat with the Zap team and see where it leads me.

**Comment by PatrickLemke** [comment]
Ok so someone from the Zap Team just got back the me. The problem is that Electron (the technology Zap is based on) is integrating the handling of links deeply in the the OS. They are using this handler to listen for clicks on lightning links:

![bildschirmfoto 2018-12-12 um 10 33 15](https://user-images.githubusercontent.com/2649936/49860116-6c45d500-fdf9-11e8-8d71-55f5ff80f380.png)

My test lead me to suggest that if the Zap app is open or minimized, it takes preference over the browser extension since the OS already catches the call before chrome does, so Joule never sees it. But if it is closed then Joule will see the call.

**Comment by wbobeirne** [comment]
I have been unable to replicate this issue, and can't implement a URI handler at the OS-level, so I'm going to close this issue. If you can replicate this in a reproducible way, let me know.
