### ISSUE TITLE
Add BTCPay Server option to onboarding

### ISSUE THREAD

**Issue by wbobeirne** [wbobeirne/joule-extension#79]
Allow users to quickly connect with the BTC pay server by providing the config string from `/server/services/lnd/BTC` and having that set them up. Make it a separate option from "local node" and "remote node" so that instructions can be laid out for them.

**Comment by CarlosRoldanx** [comment]
Nice @wbobeirne !

**Comment by NicolasDorier** [comment]
Documenting here:

The user can copy paste a connnection string with the following form:

```
config=https://mainnet.demo.btcpayserver.org/lnd-config/30027837828/lnd.config
```

Such `https://mainnet.demo.btcpayserver.org/lnd-config/30027837828/lnd.config` is a link which expires after 5 minutes, so you need to fetch the configuration from `https://mainnet.demo.btcpayserver.org/lnd-config/30027837828/lnd.config`.

What you get is something like this

```json
{  
   "configurations":[  
      {  
         "chainType":"Mainnet",
         "type":"lnd-rest",
         "cryptoCode":"BTC",
         "uri":"https://mainnet.demo.btcpayserver.org/lnd-rest/btc/",
         "macaroon":"020304020...ab03",
         "certificateThumbprint":null,
         "restrictedMacaroon":"0201....05"
      }
   ]
}
```

The `macaroon` is in `hex`.  In some installs `restrictedMacaroon`  will be `null`. If that's the case, you should use `macaroon` as both the readonly macaroon and admin macaroon.
If `restrictedMacaroon` is not null, it is an invoice macaroon.
