### ISSUE TITLE
Rename Deposit to Add funds

### ISSUE THREAD

**Issue by bitcoinuser** [wbobeirne/joule-extension#81]
Rename Deposit to Add funds

**Comment by wbobeirne** [comment]
This feels a little semantic to me, and I haven't had anyone ask how this works nor do I see a compelling difference in the copy, so I think I'm going to leave as-is. Let me know if you feel this is important for any reason.

**Comment by bitcoinuser** [comment]
I like words less technical, but I have no problem with Deposit. So I'll close it.
