### ISSUE TITLE
[Wiki] Documentation change for Firefox on macOS

### ISSUE THREAD

**Issue by janoside** [wbobeirne/joule-extension#82]
The wiki's manual installation instructions indicate that Firefox users should navigate to `about:addons` - on Firefox 63 on macOS, the UI to enable addon debugging and loading temporary addons is at `about:debugging`. Making an optional note of this difference in the wiki would probably help others with similar environments.

**Comment by wbobeirne** [comment]
Thanks, that cuts out a step. Updated the wiki.
