### ISSUE TITLE
How can I get node url of lnd?

### ISSUE THREAD

**Issue by jiyu3** [wbobeirne/joule-extension#88]
Hi,

I installed lnd in my cloud server, and it's working on lnd.green.

So I try to set up Joule with remote server on Chrome, but I don't know what to input on filed "Node URL" on "Provide a URL" screen below.
<img width="684" alt="2018-12-12 15 46 23" src="https://user-images.githubusercontent.com/11806750/49851700-4e8e6500-fe25-11e8-913e-c4bcfd4428bf.png">

What is node url on lnd?

My lnd.conf is:
```
[Application Options]
externalip=35.211.30.191:9999
listen=0.0.0.0:9999
listen=[::1]:9998
rpclisten=0.0.0.0:10009

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
```

**Comment by PatrickLemke** [comment]
Joule uses the REST API so you need to set restlisten=0.0.0.0:8080 (or some other open port) in your lnd.conf. In this example your node url would be https://35.211.30.191:8080. You need to also make sure that your firewall doesn't block the port you want to use.

**Comment by wbobeirne** [comment]
@PatrickLemke has it right. Personally I have an nginx webserver in front of my node as well, to make it easier to configure and so I can keep all of my external traffic routed through that. But just configuring & opening up `8080` works totally fine.

I'm going to close this issue just for house-keeping purposes, but feel free to ask any questions here about getting your remote node connected.
