### ISSUE TITLE
What is the proper setting for tlsextraip and restlisten?

### ISSUE THREAD

**Issue by karzak** [wbobeirne/joule-extension#97]
My external domain is, for example, 34.222.33.44 

In my lnd.conf, I have the `tlsextraip` set to 34.222.33.44 and my `restlisten` set to 0.0.0.0:8080

When I tried to connect to Joule, I had to change my `tlsextraip` to 0.0.0.0 in order to get the tls handshake to work. This broke my ability to connect to that node with Zap. Is that the correct configuration, or should I have used other values that would not have required me to regenerate the tls.cert?

**Comment by wbobeirne** [comment]
The current behavior of Joule is to have you circumvent SSL by telling the browser to ignore the self-signed cert warning. While I plan to change this in the future, that means in the mean time the TLS settings shouldn't have an effect on Joule connection.

**Comment by wbobeirne** [comment]
Somebody hit me up on Twitter with this same issue, and we were able to work through it. The answer is that you can set multiple `tlsextraip`s in your config, so yours would look like:

```
tlsextraip=0.0.0.0
tlsextraip=34.222.33.44
```

That should do it for you!
