### ISSUE TITLE
Feature request: option to share (p2p) anonymously payment data between Joule users.

### ISSUE THREAD

**Issue by bitcoinuser** [wbobeirne/joule-extension#98]
Hi,

I don't know if is possible (maybe webrtc), but will be great have an option to share (p2p) anonymously payment data between Joule users.

Data to be shared between the users: 
Sites that was used by Joule users for payments.

**Comment by jnewbery** [comment]
Seems out of scope to me.

Joule currently does one thing really well. I think it should stay that way :)

**Comment by bitcoinuser** [comment]
I think it's important to know which sites accept Bitcoin Lightning. I added most of the sites listed on http://lightningnetworkstores.com/. I think this should be a automatically process. I'm sure Joule users will like this a lot.

**Comment by wbobeirne** [comment]
If there's any kind of app browser, I'll just keep it to manual curation, or user submissions. Putting together a peer to peer network just to share that kind of information sounds like a huge technical hassle, without a lot of payoff. And it looks like that site is doing a pretty good job already of exposing and surfacing cool lightning apps!

**Comment by jnewbery** [comment]
> it looks like that site is doing a pretty good job already of exposing and surfacing cool lightning apps!

:+1: thanks for sharing, @bitcoinuser !
