### ISSUE TITLE
Firefox does not bypass CORS

### ISSUE THREAD

**Issue by wbobeirne** [wbobeirne/joule-extension#99]
### Description of the Issue

Firefox does not bypass CORS even if the URL has been given full permissions by the user. This differs from how Chrome and Opera operate. I've filed a bugzilla report for the issue (https://bugzilla.mozilla.org/show_bug.cgi?id=1514963) as well as an issue on LND to add CORS headers (https://github.com/lightningnetwork/lnd/issues/2344) but in the mean time, I'm not entirely sure how to get around this. I believe that using `webRequest` may allow me to forcibly add the headers in, but I couldn't seem to get it to work with my limited attempts.

### Steps to Reproduce

Connect to an lnd instance directly in Firefox, see the CORS warning in your console.

### Console Logs / Screenshots

<img width="786" alt="screen shot 2018-12-18 at 10 44 51 pm" src="https://user-images.githubusercontent.com/649992/50197766-96762600-0316-11e9-82b4-d6cddc58cc34.png">

**Comment by jamesob** [comment]
Would it be possible for Joule to accept the `tls.cert` that LND generates (in the same way it does macaroons) and register it with the browser as a recognized certificate authority? That seems like the long-term fix for this, but I sort of doubt browser extensions are permitted to do this.

Short of that, we might be able to instruct the user to do that manually (which is really what they should be doing anyway). I can file a PR if you think that's the right route to go.
